                                    -- V1__init_schema.sql

                                    CREATE TABLE master_apps (
                                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(255) NOT NULL UNIQUE,
                                        description VARCHAR(255),
                                        contact_email VARCHAR(255),
                                        created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        updated_at TIMESTAMP(6),
                                        deleted_at TIMESTAMP(6)
                                    );

                                    CREATE TABLE client_apps (
                                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(255) NOT NULL UNIQUE,
                                        api_key VARCHAR(255) NOT NULL UNIQUE,
                                        mfa_policy VARCHAR(255) DEFAULT 'DISABLED',
                                        master_app_id INTEGER REFERENCES master_apps(id),
                                        created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        updated_at TIMESTAMP(6),
                                        deleted_at TIMESTAMP(6)
                                    );

                                    CREATE TABLE users (
                                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        email VARCHAR(255) NOT NULL UNIQUE,
                                        password VARCHAR(255) NOT NULL,
                                        first_name VARCHAR(255) NOT NULL,
                                        last_name VARCHAR(255) NOT NULL,
                                        username VARCHAR(255) NOT NULL UNIQUE,
                                        date_of_birth TIMESTAMP(6) NOT NULL,
                                        client_app_id INTEGER NOT NULL REFERENCES client_apps(id),

                                        enabled BOOLEAN DEFAULT TRUE,
                                        account_locked BOOLEAN DEFAULT FALSE,
                                        mfa_enabled BOOLEAN DEFAULT FALSE,
                                        mfa_secret VARCHAR(255),
                                        verification_code VARCHAR(255),
                                        reset_password_token VARCHAR(255),
                                        reset_password_token_expiry TIMESTAMP(6),

                                        created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        updated_at TIMESTAMP(6),
                                        deleted_at TIMESTAMP(6),

                                        -- Constraint única compuesta (un email único por tenant, o global según tu lógica actual)
                                        CONSTRAINT uk_user_credential_app UNIQUE (email, client_app_id)
                                    );

                                    CREATE TABLE roles (
                                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(255) NOT NULL,
                                        client_app_id INTEGER NOT NULL REFERENCES client_apps(id),
                                        creator_user_id INTEGER NOT NULL REFERENCES users(id),
                                        created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        updated_at TIMESTAMP(6),
                                        deleted_at TIMESTAMP(6),
                                        CONSTRAINT uk_role_name_per_tenant UNIQUE (name, client_app_id)
                                    );

                                    CREATE TABLE permissions (
                                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(255) NOT NULL UNIQUE,
                                        is_sys_only BOOLEAN DEFAULT FALSE,
                                        created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        updated_at TIMESTAMP(6),
                                        deleted_at TIMESTAMP(6)
                                    );

                                    CREATE TABLE users_roles (
                                        user_id INTEGER NOT NULL REFERENCES users(id),
                                        roles_id INTEGER NOT NULL REFERENCES roles(id),
                                        PRIMARY KEY (user_id, roles_id)
                                    );

                                    CREATE TABLE roles_permissions (
                                        role_id INTEGER NOT NULL REFERENCES roles(id),
                                        permission_id INTEGER NOT NULL REFERENCES permissions(id),
                                        PRIMARY KEY (role_id, permission_id)
                                    );

                                    CREATE TABLE tokens (
                                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        token VARCHAR(255) UNIQUE,
                                        revoked BOOLEAN,
                                        expired BOOLEAN,
                                        user_id INTEGER REFERENCES users(id),
                                        device_info VARCHAR(255),
                                        ip_adress VARCHAR(255)
                                    );

                                    CREATE TABLE audit_logs (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        action VARCHAR(255) NOT NULL,
                                        email VARCHAR(255) NOT NULL,
                                        timestamp TIMESTAMP(6) NOT NULL,
                                        ip_adress VARCHAR(255),
                                        description VARCHAR(255),
                                        client_app_name VARCHAR(255)
                                    );

                                    CREATE TABLE password_history (
                                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        password VARCHAR(255) NOT NULL,
                                        created_at TIMESTAMP(6) NOT NULL,
                                        user_id INTEGER NOT NULL REFERENCES users(id)
                                    );