CREATE TABLE client_apps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    api_key VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    PRIMARY KEY (id)
);
ALTER TABLE client_apps ADD CONSTRAINT uc_client_apps_api_key UNIQUE (api_key);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    account_locked BOOLEAN,
    client_app_id INTEGER NOT NULL,
    date_of_birth TIMESTAMP(6) NOT NULL,
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    verification_code VARCHAR(255),
    reset_password_token VARCHAR(255),
    reset_password_token_expiry TIMESTAMP(6),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    PRIMARY KEY (id)
);
ALTER TABLE users ADD CONSTRAINT uc_users_username UNIQUE (username);
ALTER TABLE users ADD CONSTRAINT uq_users_email_client_app UNIQUE (email, client_app_id);
ALTER TABLE users ADD CONSTRAINT fk_users_client_app FOREIGN KEY (client_app_id) REFERENCES client_apps(id);

CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    client_app_id INTEGER NOT NULL,
    creator_user_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    PRIMARY KEY (id)
);
ALTER TABLE roles ADD CONSTRAINT fk_roles_client_app FOREIGN KEY (client_app_id) REFERENCES client_apps(id);
ALTER TABLE roles ADD CONSTRAINT fk_roles_creator_user FOREIGN KEY (creator_user_id) REFERENCES users(id);

CREATE TABLE permissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    isSysOnly BOOLEAN DEFAULT FALSE,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP,
     deleted_at TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE users_roles (user_id INTEGER NOT NULL, roles_id INTEGER NOT NULL);
ALTER TABLE users_roles ADD CONSTRAINT fk_users_roles_role FOREIGN KEY (roles_id) REFERENCES roles(id);
ALTER TABLE users_roles ADD CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) REFERENCES users(id);

CREATE TABLE roles_permissions (role_id INTEGER NOT NULL, permission_id INTEGER NOT NULL);
ALTER TABLE roles_permissions ADD CONSTRAINT fk_roles_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id);
ALTER TABLE roles_permissions ADD CONSTRAINT fk_roles_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id);

CREATE TABLE token (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    expired BOOLEAN NOT NULL,
    revoked BOOLEAN NOT NULL,
    token VARCHAR(255) UNIQUE,
    token_type VARCHAR(255),
    user_id INTEGER,
    PRIMARY KEY (id)
);
ALTER TABLE token ADD CONSTRAINT fk_token_user FOREIGN KEY (user_id) REFERENCES users(id);